// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ChatClient.Core.Common.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ChatClient.Core.Common.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        public static string NotesPlaceholder {
            get {
                return ResourceManager.GetString("NotesPlaceholder", resourceCulture);
            }
        }
        
        public static string AddFunds {
            get {
                return ResourceManager.GetString("AddFunds", resourceCulture);
            }
        }
        
        public static string PickerName {
            get {
                return ResourceManager.GetString("PickerName", resourceCulture);
            }
        }
        
        public static string EnterCorrectFundSum {
            get {
                return ResourceManager.GetString("EnterCorrectFundSum", resourceCulture);
            }
        }
        
        public static string IncorrectSum {
            get {
                return ResourceManager.GetString("IncorrectSum", resourceCulture);
            }
        }
        
        public static string RemoveWarning {
            get {
                return ResourceManager.GetString("RemoveWarning", resourceCulture);
            }
        }
        
        public static string EnterGroupNominal {
            get {
                return ResourceManager.GetString("EnterGroupNominal", resourceCulture);
            }
        }
        
        public static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        public static string EnterGroupName {
            get {
                return ResourceManager.GetString("EnterGroupName", resourceCulture);
            }
        }
        
        public static string YouDidNotSelectImageForGroup {
            get {
                return ResourceManager.GetString("YouDidNotSelectImageForGroup", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ListOfGroups {
            get {
                return ResourceManager.GetString("ListOfGroups", resourceCulture);
            }
        }
        
        public static string ByEndingTime {
            get {
                return ResourceManager.GetString("ByEndingTime", resourceCulture);
            }
        }
        
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        public static string EndingGroupQuestion {
            get {
                return ResourceManager.GetString("EndingGroupQuestion", resourceCulture);
            }
        }
        
        public static string NewMember {
            get {
                return ResourceManager.GetString("NewMember", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        public static string MyGroups {
            get {
                return ResourceManager.GetString("MyGroups", resourceCulture);
            }
        }
        
        public static string Dialogs {
            get {
                return ResourceManager.GetString("Dialogs", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string HowToAddFunds {
            get {
                return ResourceManager.GetString("HowToAddFunds", resourceCulture);
            }
        }
        
        public static string GroupWillEnd {
            get {
                return ResourceManager.GetString("GroupWillEnd", resourceCulture);
            }
        }
        
        public static string EnterCorrectSum {
            get {
                return ResourceManager.GetString("EnterCorrectSum", resourceCulture);
            }
        }
        
        public static string MakeContribution {
            get {
                return ResourceManager.GetString("MakeContribution", resourceCulture);
            }
        }
        
        public static string DiscussInChat {
            get {
                return ResourceManager.GetString("DiscussInChat", resourceCulture);
            }
        }
        
        public static string GroupNominal {
            get {
                return ResourceManager.GetString("GroupNominal", resourceCulture);
            }
        }
        
        public static string UntilGroupEnd {
            get {
                return ResourceManager.GetString("UntilGroupEnd", resourceCulture);
            }
        }
        
        public static string CurrentFund {
            get {
                return ResourceManager.GetString("CurrentFund", resourceCulture);
            }
        }
        
        public static string NumberOfMembers {
            get {
                return ResourceManager.GetString("NumberOfMembers", resourceCulture);
            }
        }
        
        public static string MessageToOwner {
            get {
                return ResourceManager.GetString("MessageToOwner", resourceCulture);
            }
        }
        
        public static string CreateNewGroup {
            get {
                return ResourceManager.GetString("CreateNewGroup", resourceCulture);
            }
        }
        
        public static string OrderGroups {
            get {
                return ResourceManager.GetString("OrderGroups", resourceCulture);
            }
        }
        
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        public static string Nominal {
            get {
                return ResourceManager.GetString("Nominal", resourceCulture);
            }
        }
        
        public static string Fund {
            get {
                return ResourceManager.GetString("Fund", resourceCulture);
            }
        }
        
        public static string LastMember {
            get {
                return ResourceManager.GetString("LastMember", resourceCulture);
            }
        }
        
        public static string BetInGroup {
            get {
                return ResourceManager.GetString("BetInGroup", resourceCulture);
            }
        }
        
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        public static string Contribution {
            get {
                return ResourceManager.GetString("Contribution", resourceCulture);
            }
        }
        
        public static string AmountOfWinnings {
            get {
                return ResourceManager.GetString("AmountOfWinnings", resourceCulture);
            }
        }
        
        public static string WinningMember {
            get {
                return ResourceManager.GetString("WinningMember", resourceCulture);
            }
        }
        
        public static string GroupOwner {
            get {
                return ResourceManager.GetString("GroupOwner", resourceCulture);
            }
        }
        
        public static string ByLastMember {
            get {
                return ResourceManager.GetString("ByLastMember", resourceCulture);
            }
        }
        
        public static string ByEndTime {
            get {
                return ResourceManager.GetString("ByEndTime", resourceCulture);
            }
        }
        
        public static string ByNominal {
            get {
                return ResourceManager.GetString("ByNominal", resourceCulture);
            }
        }
        
        public static string ByFundNominal {
            get {
                return ResourceManager.GetString("ByFundNominal", resourceCulture);
            }
        }
        
        public static string AccountAmount {
            get {
                return ResourceManager.GetString("AccountAmount", resourceCulture);
            }
        }
        
        public static string AccountID {
            get {
                return ResourceManager.GetString("AccountID", resourceCulture);
            }
        }
        
        public static string RestoreAccount {
            get {
                return ResourceManager.GetString("RestoreAccount", resourceCulture);
            }
        }
        
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        public static string RemoveGroup {
            get {
                return ResourceManager.GetString("RemoveGroup", resourceCulture);
            }
        }
        
        public static string EnterSumFromTo {
            get {
                return ResourceManager.GetString("EnterSumFromTo", resourceCulture);
            }
        }
        
        public static string SelectPhotoLocation {
            get {
                return ResourceManager.GetString("SelectPhotoLocation", resourceCulture);
            }
        }
        
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        public static string SelectPhoto {
            get {
                return ResourceManager.GetString("SelectPhoto", resourceCulture);
            }
        }
        
        public static string EmailCheck {
            get {
                return ResourceManager.GetString("EmailCheck", resourceCulture);
            }
        }
        
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        public static string CodeCheck {
            get {
                return ResourceManager.GetString("CodeCheck", resourceCulture);
            }
        }
        
        public static string ConfirmCode {
            get {
                return ResourceManager.GetString("ConfirmCode", resourceCulture);
            }
        }
        
        public static string StatusMessage {
            get {
                return ResourceManager.GetString("StatusMessage", resourceCulture);
            }
        }
        
        public static string GroupEnded {
            get {
                return ResourceManager.GetString("GroupEnded", resourceCulture);
            }
        }
        
        public static string NeedInternetConnection {
            get {
                return ResourceManager.GetString("NeedInternetConnection", resourceCulture);
            }
        }
        
        public static string RemoteServerUnavailable {
            get {
                return ResourceManager.GetString("RemoteServerUnavailable", resourceCulture);
            }
        }
        
        public static string AuthorizationError {
            get {
                return ResourceManager.GetString("AuthorizationError", resourceCulture);
            }
        }
        
        public static string PhotoSizeUnavailable {
            get {
                return ResourceManager.GetString("PhotoSizeUnavailable", resourceCulture);
            }
        }
        
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string RulesText {
            get {
                return ResourceManager.GetString("RulesText", resourceCulture);
            }
        }
    }
}
